import { MigrationInterface, QueryRunner } from "typeorm";

export class Store1744202907331 implements MigrationInterface {
    name = 'Store1744202907331'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "external_category_seller" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "store_name" character varying NOT NULL, "store_category_url" character varying NOT NULL, "store_category_english_name" character varying NOT NULL, "store_category_persian_name" character varying NOT NULL, "category_id" integer NOT NULL, CONSTRAINT "PK_7a084061e64fe27e7a29a35d6d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aa6061f8419fc181b3eee5eb6e" ON "external_category_seller" ("category_id") `);
        await queryRunner.query(`CREATE TABLE "category" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying NOT NULL, "description" character varying, "image" character varying, "parent_id" integer, "nsleft" integer NOT NULL DEFAULT '1', "nsright" integer NOT NULL DEFAULT '2', CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_inventory_type_enum" AS ENUM('input', 'output', 'transfer')`);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "inventory_number" integer NOT NULL, "inventory_date" TIMESTAMP WITH TIME ZONE NOT NULL, "inventory_type" "public"."inventory_inventory_type_enum" NOT NULL DEFAULT 'input', "inventory_description" character varying, "created_by_user_id" integer, "updated_by_user_id" integer, CONSTRAINT "PK_82aa5da437c5bbfb80703b08309" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_47dd1d495db9c7f9d13a5ac8f3" ON "inventory" ("inventory_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_2924578ee534eb29c8a63079dc" ON "inventory" ("inventory_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a9cc5bdaaa56436c12b5ed005" ON "inventory" ("created_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_12480d0acba854455664f075ff" ON "inventory" ("updated_by_user_id") `);
        await queryRunner.query(`CREATE TABLE "warehouse" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "title" character varying NOT NULL, "is_virtualy" boolean NOT NULL DEFAULT false, "address" character varying, "image" character varying, "description" character varying, CONSTRAINT "PK_965abf9f99ae8c5983ae74ebde8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "quantity" integer NOT NULL, "available_quantity" integer NOT NULL DEFAULT '0', "warehouse_id" integer NOT NULL, "product_id" integer NOT NULL, CONSTRAINT "PK_092bc1fc7d860426a1dec5aa8e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b2be25bd3e78455fe801c45e89" ON "stock" ("warehouse_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_375ba760c8cff338fc8c94b416" ON "stock" ("product_id") `);
        await queryRunner.query(`CREATE TYPE "public"."inventory_item_unit_enum" AS ENUM('number', 'kg', 'm', 'box', 'roll', 'device')`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_item_operator_type_enum" AS ENUM('positive', 'negative')`);
        await queryRunner.query(`CREATE TABLE "inventory_item" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "unit" "public"."inventory_item_unit_enum" NOT NULL DEFAULT 'device', "quantity" integer NOT NULL, "description" character varying, "operator_type" "public"."inventory_item_operator_type_enum" NOT NULL DEFAULT 'positive', "warehouse_id" integer NOT NULL, "warehouse_from_id" integer, "warehouse_to_id" integer, "inventory_id" integer NOT NULL, "product_id" integer NOT NULL, "order_item_id" integer, "stockId" integer, CONSTRAINT "REL_37cda1bfa628475af0cea7d493" UNIQUE ("stockId"), CONSTRAINT "PK_94f5cbcb5f280f2f30bd4a9fd90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fd584d70d436caaa239e7b7f8f" ON "inventory_item" ("operator_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_731aaa395a59ab73f15bceab4c" ON "inventory_item" ("warehouse_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b48e3354feb830df03c8d82c9c" ON "inventory_item" ("warehouse_from_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7686bde658a6de072c3d3f5f3" ON "inventory_item" ("warehouse_to_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a2129b235bd560a0a725ae3404" ON "inventory_item" ("inventory_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b70c6bca6b0d4605c55182660a" ON "inventory_item" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_70a90ff2966871b324b13137f0" ON "inventory_item" ("order_item_id") `);
        await queryRunner.query(`CREATE TYPE "public"."review_recommended_enum" AS ENUM('unknown', 'recommended', 'not_recommended', 'not_sure')`);
        await queryRunner.query(`CREATE TABLE "review" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "title" character varying, "content" character varying NOT NULL, "rating" integer NOT NULL DEFAULT '0', "pros" text, "cons" text, "images" jsonb, "videos" jsonb, "recommended" "public"."review_recommended_enum" NOT NULL DEFAULT 'unknown', "is_anonymous" boolean NOT NULL DEFAULT false, "user_has_bought_product" boolean NOT NULL DEFAULT false, "user_id" integer NOT NULL, "product_code" character varying NOT NULL, "product_id" integer NOT NULL, CONSTRAINT "PK_2e4299a343a81574217255c00ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_81446f2ee100305f42645d4d6c" ON "review" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a20ed20359d487a9f98f4b941a" ON "review" ("product_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_26b533e15b5f2334c96339a1f0" ON "review" ("product_id") `);
        await queryRunner.query(`CREATE TABLE "question" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "question_text" text, "user_has_bought_product" boolean NOT NULL DEFAULT false, "user_id" integer NOT NULL, "product_code" character varying NOT NULL, "product_id" integer NOT NULL, CONSTRAINT "PK_21e5786aa0ea704ae185a79b2d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_82c53e1db067ff3d6ef17dfd5c" ON "question" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1db4a01e852077f921e6fc490" ON "question" ("product_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_baf8880ea77600518cfc1db65b" ON "question" ("product_id") `);
        await queryRunner.query(`CREATE TABLE "specification" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "key" character varying NOT NULL, "value" character varying NOT NULL, "key_2" character varying, "value_2" character varying, "product_id" integer NOT NULL, CONSTRAINT "PK_01b2d90197e187e3187b2d888be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_28e745d2bcfde9e83c22c6b14f" ON "specification" ("key") `);
        await queryRunner.query(`CREATE INDEX "IDX_6452053c9548b0ae00102d90b6" ON "specification" ("key_2") `);
        await queryRunner.query(`CREATE TABLE "external_seller" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "store_name" character varying NOT NULL, "store_product_url" character varying NOT NULL, "product_id" integer NOT NULL, CONSTRAINT "PK_72dfe2a08dd0de595dee5471005" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_37d4681a8df569c3aa1e360ca0" ON "external_seller" ("store_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_eae0a7adac2f3f973cf9528b21" ON "external_seller" ("store_product_url") `);
        await queryRunner.query(`CREATE INDEX "IDX_4fc98ab53f438ddf2d40785c81" ON "external_seller" ("product_id") `);
        await queryRunner.query(`CREATE TABLE "packaging_cost" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "title" character varying NOT NULL, "cost" numeric(15,0) NOT NULL DEFAULT '0', "shared_packaging" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_8ccab6e8df8c62b716959d94f9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."product_product_type_enum" AS ENUM('unknown', 'original', 'copy', 'renew')`);
        await queryRunner.query(`CREATE TYPE "public"."product_unit_enum" AS ENUM('number', 'kg', 'm', 'box', 'roll', 'device')`);
        await queryRunner.query(`CREATE TABLE "product" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "product_code" character varying, "name" character varying NOT NULL, "description" character varying NOT NULL, "image" character varying, "images" character varying array, "datasheet" character varying, "part_number" character varying, "product_type" "public"."product_product_type_enum" NOT NULL DEFAULT 'unknown', "keywords" jsonb NOT NULL DEFAULT '[]', "sale_price" numeric(15,0) NOT NULL DEFAULT '0', "discount_percentage" numeric(5,2) NOT NULL DEFAULT '0', "discount_amount" numeric(15,0) NOT NULL DEFAULT '0', "price_scale_value" numeric(15,6) NOT NULL DEFAULT '1', "is_scalable_price" boolean NOT NULL DEFAULT true, "unit" "public"."product_unit_enum" NOT NULL DEFAULT 'device', "is_active" boolean NOT NULL DEFAULT false, "is_online_payment_allowed" boolean NOT NULL DEFAULT false, "category_id" integer, "packaging_cost_id" integer, CONSTRAINT "PK_bebc9158e480b949565b4dc7a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fb912a8e66bfe036057ba4651f" ON "product" ("product_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_22cc43e9a74d7498546e9a63e7" ON "product" ("name") `);
        await queryRunner.query(`CREATE TABLE "order_item" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "sale_price" numeric(15,0) NOT NULL DEFAULT '0', "quantity" integer NOT NULL, "bonus_data" jsonb, "order_id" integer NOT NULL, "product_id" integer, CONSTRAINT "PK_d01158fe15b1ead5c26fd7f4e90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e9674a6053adbaa1057848cddf" ON "order_item" ("order_id") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_payment_status_enum" AS ENUM('pending', 'confirmed', 'rejected')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_payment_type_enum" AS ENUM('receipt', 'debit', 'online')`);
        await queryRunner.query(`CREATE TABLE "payment" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "payment_status" "public"."payment_payment_status_enum" NOT NULL DEFAULT 'pending', "payment_type" "public"."payment_payment_type_enum" NOT NULL DEFAULT 'receipt', "payment_order_id" character varying NOT NULL, "amount" numeric(15,0) NOT NULL DEFAULT '0', "payment_amount" numeric(15,0) NOT NULL DEFAULT '0', "description" character varying(255), "attach_url" character varying, "rejected_note" character varying, "payment_provider_data" jsonb, "order_id" integer NOT NULL, "user_id" integer NOT NULL, "confirmed_rejected_by_user_id" integer, CONSTRAINT "UQ_3d4f2c0ac1d61c47428a9dffc40" UNIQUE ("payment_order_id"), CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c66c60a17b56ec882fcd8ec770" ON "payment" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_35b723a7893b3168736539356e" ON "payment" ("confirmed_rejected_by_user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."delivery_method_delivery_type_enum" AS ENUM('post_normal', 'post_fast', 'tipax', 'rider', 'self_pickup')`);
        await queryRunner.query(`CREATE TYPE "public"."delivery_method_delivery_charge_type_enum" AS ENUM('prepaid', 'cod')`);
        await queryRunner.query(`CREATE TYPE "public"."delivery_method_delivery_pricing_type_enum" AS ENUM('fixed', 'selected_area', 'per_kilometer')`);
        await queryRunner.query(`CREATE TABLE "delivery_method" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "delivery_type" "public"."delivery_method_delivery_type_enum" NOT NULL DEFAULT 'post_normal', "delivery_charge_type" "public"."delivery_method_delivery_charge_type_enum" NOT NULL DEFAULT 'prepaid', "delivery_pricing_type" "public"."delivery_method_delivery_pricing_type_enum" NOT NULL DEFAULT 'fixed', "fixed_price" numeric(15,0) DEFAULT '0', "per_kilometer" numeric(15,0) DEFAULT '0', "delivery_method_area_rules" jsonb NOT NULL DEFAULT '[]', "is_enabled" boolean NOT NULL DEFAULT false, "description" character varying, CONSTRAINT "PK_8bad1c538ff561c66e1db629c5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."delivery_delivery_type_enum" AS ENUM('post_normal', 'post_fast', 'tipax', 'rider', 'self_pickup')`);
        await queryRunner.query(`CREATE TYPE "public"."delivery_delivery_status_enum" AS ENUM('pending', 'confirmed', 'rejected', 'in_transit', 'delivered')`);
        await queryRunner.query(`CREATE TABLE "delivery" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "delivery_method_id" integer NOT NULL, "delivery_method_area_rule_area_name" character varying, "delivery_type" "public"."delivery_delivery_type_enum" NOT NULL DEFAULT 'post_normal', "delivery_started_date" TIMESTAMP WITH TIME ZONE, "delivery_delivered_date" TIMESTAMP WITH TIME ZONE, "delivery_address" character varying, "delivery_city" character varying, "delivery_postal_code" character varying, "delivery_note" character varying, "delivery_latitude" double precision, "delivery_longitude" double precision, "driver_name" character varying, "driver_phone_number" character varying, "car_license_plate" character varying, "recipient_name" character varying, "recipient_national_id" character varying, "recipient_phone_number" character varying, "recipient_mobile_phone_number" character varying, "delivery_status" "public"."delivery_delivery_status_enum" NOT NULL DEFAULT 'pending', "confirmed" boolean NOT NULL DEFAULT false, "confirmation_date" TIMESTAMP WITH TIME ZONE, "rejected_note" character varying, "user_id" integer NOT NULL, "confirmed_rejected_by_user_id" integer, CONSTRAINT "PK_ffad7bf84e68716cd9af89003b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c1e327ff0d4c0ee80c8d3aaba5" ON "delivery" ("delivery_method_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3b8af1ce2f6e143d416d83080" ON "delivery" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_df1b789b42b286ca4c329645bf" ON "delivery" ("confirmed_rejected_by_user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transaction_transaction_type_enum" AS ENUM('credit', 'debit')`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transaction_transaction_note_enum" AS ENUM('discount_profit', 'bonus_profit')`);
        await queryRunner.query(`CREATE TABLE "wallet_transaction" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "amount" numeric(15,0) NOT NULL DEFAULT '0', "transaction_type" "public"."wallet_transaction_transaction_type_enum" NOT NULL, "transaction_note" "public"."wallet_transaction_transaction_note_enum" NOT NULL, "user_id" integer NOT NULL, "order_id" integer NOT NULL, CONSTRAINT "PK_62a01b9c3a734b96a08c621b371" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1b321310b8544083f5811cd228" ON "wallet_transaction" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8e10a769976c7b2bf36c07c8be" ON "wallet_transaction" ("order_id") `);
        await queryRunner.query(`CREATE TYPE "public"."contact_contact_type_enum" AS ENUM('individual', 'enterprise')`);
        await queryRunner.query(`CREATE TABLE "contact" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "contact_type" "public"."contact_contact_type_enum" NOT NULL DEFAULT 'individual', "title" character varying, "name" character varying NOT NULL, "phone" character varying, "mobile_phone" character varying, "address" character varying, "city" character varying, "postal_code" character varying, "national_code" character varying, "economic_code" character varying, "latitude" double precision, "longitude" double precision, "user_id" integer NOT NULL, CONSTRAINT "PK_2cbbe00f59ab6b3bb5b8d19f989" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_33d4fc93803e7192e150216fff" ON "contact" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."order_order_status_enum" AS ENUM('pending', 'confirmed', 'rejected', 'paid', 'processing', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "order" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "order_status" "public"."order_order_status_enum" NOT NULL DEFAULT 'pending', "order_invoice_number" numeric, "order_bank_identifier_code" numeric, "subtotal" numeric(15,0) NOT NULL DEFAULT '0', "packaging_cost" numeric(15,0) NOT NULL DEFAULT '0', "delivery_cost" numeric(15,0) NOT NULL DEFAULT '0', "discount_percentage" numeric(5,2) NOT NULL DEFAULT '0', "discount_amount" numeric(15,0) NOT NULL DEFAULT '0', "user_profit_discount_percentage" numeric(5,2) NOT NULL DEFAULT '0', "user_profit_discount_amount" numeric(15,0) NOT NULL DEFAULT '0', "tax_on_profit_percentage_default" numeric NOT NULL DEFAULT '0', "tax_rate_percentage" numeric NOT NULL DEFAULT '0', "tax_amount" numeric(15,0) NOT NULL DEFAULT '0', "round_amount" numeric(15,0) NOT NULL DEFAULT '0', "total" numeric(15,0) NOT NULL DEFAULT '0', "note" character varying, "is_paid" boolean NOT NULL DEFAULT false, "rejected_note" character varying, "share_code" character varying, "pdf_file_name" character varying, "pdf_file_url" character varying, "delivery_date" TIMESTAMP WITH TIME ZONE, "due_date" TIMESTAMP WITH TIME ZONE, "user_id" integer NOT NULL, "contact_id" integer, "contact_snapshot" jsonb, "billing_contact_id" integer, "billing_contact_snapshot" jsonb, "is_confirmed_rejected_by_system" boolean NOT NULL DEFAULT false, "confirmed_rejected_by_user_id" integer, "delivery_id" integer, CONSTRAINT "UQ_693dc280688fb9977a88cc7db0c" UNIQUE ("order_invoice_number"), CONSTRAINT "REL_962eec87d3d029c51525f259fb" UNIQUE ("delivery_id"), CONSTRAINT "PK_1031171c13130102495201e3e20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_199e32a02ddc0f47cd93181d8f" ON "order" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_04ec30f762773255afc023e652" ON "order" ("contact_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c579c17491158a75f1a9fbdc0" ON "order" ("billing_contact_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b369a3afedf6dcce415eee3052" ON "order" ("confirmed_rejected_by_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_962eec87d3d029c51525f259fb" ON "order" ("delivery_id") `);
        await queryRunner.query(`CREATE TABLE "wallet" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "balance" numeric(15,0) NOT NULL DEFAULT '0', "user_id" integer NOT NULL, CONSTRAINT "UQ_72548a47ac4a996cd254b082522" UNIQUE ("user_id"), CONSTRAINT "PK_bec464dd8d54c39c54fd32e2334" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_72548a47ac4a996cd254b08252" ON "wallet" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."short_message_title_type_enum" AS ENUM('code_account_1', 'code_account_2', 'code_account_3', 'code_account_4', 'code_account_5', 'code_order_1', 'code_order_2', 'code_order_3', 'code_order_4', 'code_order_5', 'code_order_6', 'code_payment_1', 'code_payment_2', 'code_payment_3', 'code_payment_4', 'code_payment_5', 'code_payment_6', 'code_delivery_1', 'code_delivery_2', 'code_delivery_3', 'code_delivery_4', 'code_delivery_5', 'code_promotion_1', 'code_promotion_2', 'code_support_1', 'code_support_2', 'code_support_3', 'code_internal_1', 'code_internal_2', 'code_internal_3')`);
        await queryRunner.query(`CREATE TABLE "short_message" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "mobile_phone" character varying NOT NULL, "title_type" "public"."short_message_title_type_enum" NOT NULL, "text_list" jsonb, "is_sent_by_system" boolean NOT NULL, "user_id" integer, CONSTRAINT "PK_359f8a2fc0daf370939d5dd26a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a4c0eb4b475bc9dbc8757e123" ON "short_message" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."user_gender_enum" AS ENUM('male', 'female', 'unknown', 'both')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "mobile_phone" character varying, "mobile_phone_is_verified" boolean NOT NULL DEFAULT false, "email" character varying, "email_is_verified" boolean NOT NULL DEFAULT false, "first_name" character varying, "last_name" character varying, "avatar" character varying, "gender" "public"."user_gender_enum" NOT NULL DEFAULT 'unknown', "created_by_system" boolean NOT NULL DEFAULT false, "need_to_set_name" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "answer" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "answer_text" text, "user_id" integer NOT NULL, "question_id" integer NOT NULL, CONSTRAINT "PK_9232db17b63fb1e94f97e5c224f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_add8ab72aec4ce5eb87fdc2740" ON "answer" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c3d19a89541e4f0813f2fe0919" ON "answer" ("question_id") `);
        await queryRunner.query(`CREATE TYPE "public"."bonus_bonus_type_enum" AS ENUM('constant', 'percentage')`);
        await queryRunner.query(`CREATE TABLE "bonus" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "title" character varying NOT NULL, "description" character varying, "bonus_type" "public"."bonus_bonus_type_enum" NOT NULL DEFAULT 'percentage', "constant_amount" numeric(15,0), "percentage_amount" numeric(5,2), "is_enabled" boolean NOT NULL DEFAULT true, "start_date" TIMESTAMP WITH TIME ZONE, "end_date" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_885c9ca672f42874b1a5cb4d9e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "setting" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "invoice_number_pre_part" numeric NOT NULL DEFAULT '0', "invoice_number_multiple" numeric NOT NULL DEFAULT '0', "tax_rate_default" numeric NOT NULL DEFAULT '0', "base_price_scale_amount" numeric(15,0) NOT NULL DEFAULT '0', "delivery_center_latitude" double precision, "delivery_center_longitude" double precision, CONSTRAINT "PK_fcb21187dc6094e24a48f677bed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bonus_allowed_users_user" ("bonusId" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "PK_0322390ce98df1a74bf7d8d4ac1" PRIMARY KEY ("bonusId", "userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_270f7d10a60112332914ff6725" ON "bonus_allowed_users_user" ("bonusId") `);
        await queryRunner.query(`CREATE INDEX "IDX_87c01499f7585835aef939137f" ON "bonus_allowed_users_user" ("userId") `);
        await queryRunner.query(`CREATE TABLE "bonus_allowed_products_product" ("bonusId" integer NOT NULL, "productId" integer NOT NULL, CONSTRAINT "PK_c89431a4209df138057af202b6a" PRIMARY KEY ("bonusId", "productId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0205621e21212938d97e74caa3" ON "bonus_allowed_products_product" ("bonusId") `);
        await queryRunner.query(`CREATE INDEX "IDX_97c6caa4569349fefcace2149a" ON "bonus_allowed_products_product" ("productId") `);
        await queryRunner.query(`ALTER TABLE "external_category_seller" ADD CONSTRAINT "FK_aa6061f8419fc181b3eee5eb6e5" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "FK_1117b4fcb3cd4abb4383e1c2743" FOREIGN KEY ("parent_id") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_1a9cc5bdaaa56436c12b5ed0058" FOREIGN KEY ("created_by_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_12480d0acba854455664f075ff2" FOREIGN KEY ("updated_by_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock" ADD CONSTRAINT "FK_b2be25bd3e78455fe801c45e892" FOREIGN KEY ("warehouse_id") REFERENCES "warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock" ADD CONSTRAINT "FK_375ba760c8cff338fc8c94b416c" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_item" ADD CONSTRAINT "FK_731aaa395a59ab73f15bceab4cd" FOREIGN KEY ("warehouse_id") REFERENCES "warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_item" ADD CONSTRAINT "FK_b48e3354feb830df03c8d82c9cd" FOREIGN KEY ("warehouse_from_id") REFERENCES "warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_item" ADD CONSTRAINT "FK_f7686bde658a6de072c3d3f5f31" FOREIGN KEY ("warehouse_to_id") REFERENCES "warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_item" ADD CONSTRAINT "FK_a2129b235bd560a0a725ae3404b" FOREIGN KEY ("inventory_id") REFERENCES "inventory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_item" ADD CONSTRAINT "FK_b70c6bca6b0d4605c55182660a7" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_item" ADD CONSTRAINT "FK_70a90ff2966871b324b13137f09" FOREIGN KEY ("order_item_id") REFERENCES "order_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_item" ADD CONSTRAINT "FK_37cda1bfa628475af0cea7d493d" FOREIGN KEY ("stockId") REFERENCES "stock"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_81446f2ee100305f42645d4d6c2" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_26b533e15b5f2334c96339a1f08" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question" ADD CONSTRAINT "FK_82c53e1db067ff3d6ef17dfd5c4" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question" ADD CONSTRAINT "FK_baf8880ea77600518cfc1db65bf" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "specification" ADD CONSTRAINT "FK_64e7a15442ac05c470bfd4349a7" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "external_seller" ADD CONSTRAINT "FK_4fc98ab53f438ddf2d40785c81a" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_0dce9bc93c2d2c399982d04bef1" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_e9e0f4cef32be5b3b7bec98a0a3" FOREIGN KEY ("packaging_cost_id") REFERENCES "packaging_cost"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_e9674a6053adbaa1057848cddfa" FOREIGN KEY ("order_id") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_5e17c017aa3f5164cb2da5b1c6b" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_f5221735ace059250daac9d9803" FOREIGN KEY ("order_id") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_c66c60a17b56ec882fcd8ec770b" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_35b723a7893b3168736539356e3" FOREIGN KEY ("confirmed_rejected_by_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery" ADD CONSTRAINT "FK_c1e327ff0d4c0ee80c8d3aaba51" FOREIGN KEY ("delivery_method_id") REFERENCES "delivery_method"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery" ADD CONSTRAINT "FK_a3b8af1ce2f6e143d416d83080a" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery" ADD CONSTRAINT "FK_df1b789b42b286ca4c329645bf1" FOREIGN KEY ("confirmed_rejected_by_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transaction" ADD CONSTRAINT "FK_1b321310b8544083f5811cd2282" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transaction" ADD CONSTRAINT "FK_8e10a769976c7b2bf36c07c8be9" FOREIGN KEY ("order_id") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact" ADD CONSTRAINT "FK_33d4fc93803e7192e150216fffb" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_199e32a02ddc0f47cd93181d8fd" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_04ec30f762773255afc023e6524" FOREIGN KEY ("contact_id") REFERENCES "contact"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_9c579c17491158a75f1a9fbdc05" FOREIGN KEY ("billing_contact_id") REFERENCES "contact"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_b369a3afedf6dcce415eee30527" FOREIGN KEY ("confirmed_rejected_by_user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_962eec87d3d029c51525f259fba" FOREIGN KEY ("delivery_id") REFERENCES "delivery"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD CONSTRAINT "FK_72548a47ac4a996cd254b082522" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "short_message" ADD CONSTRAINT "FK_9a4c0eb4b475bc9dbc8757e1230" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answer" ADD CONSTRAINT "FK_add8ab72aec4ce5eb87fdc2740d" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answer" ADD CONSTRAINT "FK_c3d19a89541e4f0813f2fe09194" FOREIGN KEY ("question_id") REFERENCES "question"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bonus_allowed_users_user" ADD CONSTRAINT "FK_270f7d10a60112332914ff67252" FOREIGN KEY ("bonusId") REFERENCES "bonus"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "bonus_allowed_users_user" ADD CONSTRAINT "FK_87c01499f7585835aef939137f8" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "bonus_allowed_products_product" ADD CONSTRAINT "FK_0205621e21212938d97e74caa33" FOREIGN KEY ("bonusId") REFERENCES "bonus"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "bonus_allowed_products_product" ADD CONSTRAINT "FK_97c6caa4569349fefcace2149aa" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "bonus_allowed_products_product" DROP CONSTRAINT "FK_97c6caa4569349fefcace2149aa"`);
        await queryRunner.query(`ALTER TABLE "bonus_allowed_products_product" DROP CONSTRAINT "FK_0205621e21212938d97e74caa33"`);
        await queryRunner.query(`ALTER TABLE "bonus_allowed_users_user" DROP CONSTRAINT "FK_87c01499f7585835aef939137f8"`);
        await queryRunner.query(`ALTER TABLE "bonus_allowed_users_user" DROP CONSTRAINT "FK_270f7d10a60112332914ff67252"`);
        await queryRunner.query(`ALTER TABLE "answer" DROP CONSTRAINT "FK_c3d19a89541e4f0813f2fe09194"`);
        await queryRunner.query(`ALTER TABLE "answer" DROP CONSTRAINT "FK_add8ab72aec4ce5eb87fdc2740d"`);
        await queryRunner.query(`ALTER TABLE "short_message" DROP CONSTRAINT "FK_9a4c0eb4b475bc9dbc8757e1230"`);
        await queryRunner.query(`ALTER TABLE "wallet" DROP CONSTRAINT "FK_72548a47ac4a996cd254b082522"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_962eec87d3d029c51525f259fba"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_b369a3afedf6dcce415eee30527"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_9c579c17491158a75f1a9fbdc05"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_04ec30f762773255afc023e6524"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_199e32a02ddc0f47cd93181d8fd"`);
        await queryRunner.query(`ALTER TABLE "contact" DROP CONSTRAINT "FK_33d4fc93803e7192e150216fffb"`);
        await queryRunner.query(`ALTER TABLE "wallet_transaction" DROP CONSTRAINT "FK_8e10a769976c7b2bf36c07c8be9"`);
        await queryRunner.query(`ALTER TABLE "wallet_transaction" DROP CONSTRAINT "FK_1b321310b8544083f5811cd2282"`);
        await queryRunner.query(`ALTER TABLE "delivery" DROP CONSTRAINT "FK_df1b789b42b286ca4c329645bf1"`);
        await queryRunner.query(`ALTER TABLE "delivery" DROP CONSTRAINT "FK_a3b8af1ce2f6e143d416d83080a"`);
        await queryRunner.query(`ALTER TABLE "delivery" DROP CONSTRAINT "FK_c1e327ff0d4c0ee80c8d3aaba51"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_35b723a7893b3168736539356e3"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_c66c60a17b56ec882fcd8ec770b"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_f5221735ace059250daac9d9803"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_5e17c017aa3f5164cb2da5b1c6b"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_e9674a6053adbaa1057848cddfa"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_e9e0f4cef32be5b3b7bec98a0a3"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_0dce9bc93c2d2c399982d04bef1"`);
        await queryRunner.query(`ALTER TABLE "external_seller" DROP CONSTRAINT "FK_4fc98ab53f438ddf2d40785c81a"`);
        await queryRunner.query(`ALTER TABLE "specification" DROP CONSTRAINT "FK_64e7a15442ac05c470bfd4349a7"`);
        await queryRunner.query(`ALTER TABLE "question" DROP CONSTRAINT "FK_baf8880ea77600518cfc1db65bf"`);
        await queryRunner.query(`ALTER TABLE "question" DROP CONSTRAINT "FK_82c53e1db067ff3d6ef17dfd5c4"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_26b533e15b5f2334c96339a1f08"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_81446f2ee100305f42645d4d6c2"`);
        await queryRunner.query(`ALTER TABLE "inventory_item" DROP CONSTRAINT "FK_37cda1bfa628475af0cea7d493d"`);
        await queryRunner.query(`ALTER TABLE "inventory_item" DROP CONSTRAINT "FK_70a90ff2966871b324b13137f09"`);
        await queryRunner.query(`ALTER TABLE "inventory_item" DROP CONSTRAINT "FK_b70c6bca6b0d4605c55182660a7"`);
        await queryRunner.query(`ALTER TABLE "inventory_item" DROP CONSTRAINT "FK_a2129b235bd560a0a725ae3404b"`);
        await queryRunner.query(`ALTER TABLE "inventory_item" DROP CONSTRAINT "FK_f7686bde658a6de072c3d3f5f31"`);
        await queryRunner.query(`ALTER TABLE "inventory_item" DROP CONSTRAINT "FK_b48e3354feb830df03c8d82c9cd"`);
        await queryRunner.query(`ALTER TABLE "inventory_item" DROP CONSTRAINT "FK_731aaa395a59ab73f15bceab4cd"`);
        await queryRunner.query(`ALTER TABLE "stock" DROP CONSTRAINT "FK_375ba760c8cff338fc8c94b416c"`);
        await queryRunner.query(`ALTER TABLE "stock" DROP CONSTRAINT "FK_b2be25bd3e78455fe801c45e892"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_12480d0acba854455664f075ff2"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_1a9cc5bdaaa56436c12b5ed0058"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "FK_1117b4fcb3cd4abb4383e1c2743"`);
        await queryRunner.query(`ALTER TABLE "external_category_seller" DROP CONSTRAINT "FK_aa6061f8419fc181b3eee5eb6e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97c6caa4569349fefcace2149a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0205621e21212938d97e74caa3"`);
        await queryRunner.query(`DROP TABLE "bonus_allowed_products_product"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87c01499f7585835aef939137f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_270f7d10a60112332914ff6725"`);
        await queryRunner.query(`DROP TABLE "bonus_allowed_users_user"`);
        await queryRunner.query(`DROP TABLE "setting"`);
        await queryRunner.query(`DROP TABLE "bonus"`);
        await queryRunner.query(`DROP TYPE "public"."bonus_bonus_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3d19a89541e4f0813f2fe0919"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_add8ab72aec4ce5eb87fdc2740"`);
        await queryRunner.query(`DROP TABLE "answer"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_gender_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a4c0eb4b475bc9dbc8757e123"`);
        await queryRunner.query(`DROP TABLE "short_message"`);
        await queryRunner.query(`DROP TYPE "public"."short_message_title_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72548a47ac4a996cd254b08252"`);
        await queryRunner.query(`DROP TABLE "wallet"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_962eec87d3d029c51525f259fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b369a3afedf6dcce415eee3052"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c579c17491158a75f1a9fbdc0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_04ec30f762773255afc023e652"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_199e32a02ddc0f47cd93181d8f"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`DROP TYPE "public"."order_order_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33d4fc93803e7192e150216fff"`);
        await queryRunner.query(`DROP TABLE "contact"`);
        await queryRunner.query(`DROP TYPE "public"."contact_contact_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e10a769976c7b2bf36c07c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b321310b8544083f5811cd228"`);
        await queryRunner.query(`DROP TABLE "wallet_transaction"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transaction_transaction_note_enum"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transaction_transaction_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df1b789b42b286ca4c329645bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3b8af1ce2f6e143d416d83080"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1e327ff0d4c0ee80c8d3aaba5"`);
        await queryRunner.query(`DROP TABLE "delivery"`);
        await queryRunner.query(`DROP TYPE "public"."delivery_delivery_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."delivery_delivery_type_enum"`);
        await queryRunner.query(`DROP TABLE "delivery_method"`);
        await queryRunner.query(`DROP TYPE "public"."delivery_method_delivery_pricing_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."delivery_method_delivery_charge_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."delivery_method_delivery_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35b723a7893b3168736539356e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c66c60a17b56ec882fcd8ec770"`);
        await queryRunner.query(`DROP TABLE "payment"`);
        await queryRunner.query(`DROP TYPE "public"."payment_payment_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_payment_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9674a6053adbaa1057848cddf"`);
        await queryRunner.query(`DROP TABLE "order_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22cc43e9a74d7498546e9a63e7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb912a8e66bfe036057ba4651f"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP TYPE "public"."product_unit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."product_product_type_enum"`);
        await queryRunner.query(`DROP TABLE "packaging_cost"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4fc98ab53f438ddf2d40785c81"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eae0a7adac2f3f973cf9528b21"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37d4681a8df569c3aa1e360ca0"`);
        await queryRunner.query(`DROP TABLE "external_seller"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6452053c9548b0ae00102d90b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28e745d2bcfde9e83c22c6b14f"`);
        await queryRunner.query(`DROP TABLE "specification"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_baf8880ea77600518cfc1db65b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1db4a01e852077f921e6fc490"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82c53e1db067ff3d6ef17dfd5c"`);
        await queryRunner.query(`DROP TABLE "question"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26b533e15b5f2334c96339a1f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a20ed20359d487a9f98f4b941a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81446f2ee100305f42645d4d6c"`);
        await queryRunner.query(`DROP TABLE "review"`);
        await queryRunner.query(`DROP TYPE "public"."review_recommended_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70a90ff2966871b324b13137f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b70c6bca6b0d4605c55182660a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2129b235bd560a0a725ae3404"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7686bde658a6de072c3d3f5f3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b48e3354feb830df03c8d82c9c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_731aaa395a59ab73f15bceab4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd584d70d436caaa239e7b7f8f"`);
        await queryRunner.query(`DROP TABLE "inventory_item"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_item_operator_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_item_unit_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_375ba760c8cff338fc8c94b416"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2be25bd3e78455fe801c45e89"`);
        await queryRunner.query(`DROP TABLE "stock"`);
        await queryRunner.query(`DROP TABLE "warehouse"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12480d0acba854455664f075ff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a9cc5bdaaa56436c12b5ed005"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2924578ee534eb29c8a63079dc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47dd1d495db9c7f9d13a5ac8f3"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_inventory_type_enum"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa6061f8419fc181b3eee5eb6e"`);
        await queryRunner.query(`DROP TABLE "external_category_seller"`);
    }

}
